[project]
name = "intro-jax-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jax>=0.9.0.1",
    "numpy>=2.4.2",
]
